title: programming docs
url: "https://thanakijwanavit.github.io"
markdown: kramdown

include: [".htaccess"]
exclude: ["node_modules", "Gemfile", "Gemfile.lock"]

# Enable plugins (GitHub Pages-safe)
plugins:
  - jekyll-paginate
  - jekyll-sitemap

# Defaults for all pages
defaults:
  - scope:
      path: ""
    values:
      layout: "page"
      toc: true
