title: programming docs
url: "https://thanakijwanavit.github.io"
markdown: kramdown

# Enable these plugins (GitHub Pages compatible)
plugins:
  - jekyll-optional-front-matter
  - jekyll-readme-index

# Process all markdown files
include:
  - "*.md"
  - "*.markdown"

# Default front matter
defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: default
      modified_time: 2024-05-20

