name: Update Index
on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * *' # Daily update

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Generate Index
        run: |
          ./generate_index.sh
      - name: Commit Changes
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add index.md
          git commit -m "Update index.md" || exit 0
          git push
